#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/icarus-bootstrap-shared"

main() {
  info "Running icarus-bootstrap"
  prepareIcarusAppFolders
  prepareIcarusDataFolders
  updateOrCreateIcarusEngineConfig
  updateOrCreateIcarusServerSettings
  prepareSteamA2sPythonLibrary
  initCrontab
  bootstrapHook

  if [ "$UPDATE_SKIP" = true ]; then
    info "UPDATE_SKIP: skipping update, starting server directly"
    supervisorctl start icarus-server
  else
    supervisorctl start icarus-updater
  fi

  info "Bootstrap complete"
}

main
