#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/icarus-bootstrap-shared"

main() {
  info "Running icarus-bootstrap"
  prepareIcarusAppFolders
  prepareIcarusDataFolders
  updateOrCreateIcarusEngineConfig
  updateOrCreateIcarusServerSettings
  prepareSteamA2sPythonLibrary
  bootstrapWine
  initCrontab
  bootstrapHook

  if [ "$UPDATE_SKIP" = true ]; then
    info "UPDATE_SKIP: skipping update, starting server directly"
    supervisorctl start icarus-server
  else
    supervisorctl start icarus-updater
  fi

  info "Bootstrap complete"
}

bootstrapWine() {
  info "bootstrap wine"
  export WINEPREFIX=$WINEPREFIX
  export WINEARCH=$WINEARCH
  export WINEPATH=$WINEPATH
  export WINEDEBUG=$WINEDEBUG

  debug "winecfg"
  winecfg -v win10 >/dev/null 2>&1
  debug "wineboot"
  wineboot --init >/dev/null 2>&1

  info "wine version: $(wine --version)"

  info "wine bootstrap finished"
}

main
